language: node_js
node_js:
  - "node"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - newman --version

script:
  - newman run https://www.getpostman.com/collections/ee4ec5013cad27877145?apikey=$POSTMAN_APIKEY --color on