language: node_js
node_js:
  - "node"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - newman --version

script:
  - newman run https://www.getpostman.com/collections/ee4ec5013cad27877145?apikey=8dd4ba32ce834aeb96f91b0034816cf9 --color on